### ISSUE TITLE
无法执行命令

### ISSUE THREAD

**Issue by keyuhong** [ImKKingshuk/LockKnife#2]
所需环境已搭建完成，但是命令无法执行

**Comment by ImKKingshuk** [comment]
which command is not executing, tell more about the issue you're facing...

but first check if your device environment is properly setup or not.

## Requirements

- macOS, Linux, Windows
- Bash-compatible environment
- Android Device with [ADB (Android Debug Bridge)](https://developer.android.com/tools/adb) enabled
- [Android SDK Platform-Tools](https://developer.android.com/tools/releases/platform-tools) installed and added to your system's PATH
- [sqlite3](https://www.sqlite.org/download.html) required for Android 10+ support

**Comment by keyuhong** [comment]
windowS系统所有环境都搭建完成，运行截图发发给你，
![可能是错误的尝试](https://github.com/user-attachments/assets/7318bcee-314b-4a99-a9eb-bcb29921ef77)
![目录](https://github.com/user-attachments/assets/273ac116-1d44-4956-b478-e288235357c7)
![终端](https://github.com/user-attachments/assets/4ddf9ff0-573b-4738-82aa-3755d2dd5c44)
有时间可以远程看看么，有偿。。。
