### ISSUE TITLE
Failed to connect 

### ISSUE THREAD

**Issue by NewbestDev** [ImKKingshuk/LockKnife#3]
Failed to connect to the device with serial number: R38F50409CY
Android version choice: <= 5
samsung sgh i437

I think it might have to do with my command prompt, it seems like it has no access to my phone via usb

**Comment by ImKKingshuk** [comment]
check if your device environment is properly setup or not.

## Requirements

- macOS, Linux, Windows
- Bash-compatible environment
- Android Device with [ADB (Android Debug Bridge)](https://developer.android.com/tools/adb) enabled
- [Android SDK Platform-Tools](https://developer.android.com/tools/releases/platform-tools) installed and added to your system's PATH
- [sqlite3](https://www.sqlite.org/download.html) required for Android 10+ support
